### PR TITLE
update default YAML, give us a working nginx server out of the box

### PR DESCRIPTION
**Pull request by dexhorthy**

### CODE REVIEW

**Review by austinchambers — APPROVED** [review]
Looks good, and definitely a step forward, but I believe it may require annotations to get it working in a cloud provider. Maybe it'd be beneficial to add the necessary annotation for one of the cloud providers so that ingress could be demonstrated easily out of the box?

**Comment by dexhorthy** [comment]
@austinchambers I'm trying to keep this as simple as possible, with an eye toward making the Quickstart guide work. FWIW I think many cloud providers can consume this ingress without annotations--which annotations did you have in mind?

**Comment by austinchambers** [comment]
@dexhorthy Totally agree with your sentiment for simplicity. Actually, I thought it required an annotation for it to work in GKE, but, after reviewing the GKE ingress docs, maybe I misremembered... If it works there as it is, then that's great. 

I suppose my point is that it'd be great to have it work out of the box in at least one environment.

**Comment by dexhorthy** [comment]
@austinchambers Gotcha, for what its worth, for this to work in GKE, you'd need to change not the ingress, but change the Service to type NodePort, which even more so feels like perhaps unnecessary complexity at this stage 🙂 . I think a better way to address existing cluster discrepancies is via doc changes in a separate "existing cluster" quickstart. 

In any case, I've pushed a few meager fixes in a followup commit, let me know what you think?

**Pull request merged**
