### PR TITLE
Align default yaml with replicated-starter-kots

### PR DESCRIPTION
**Pull request by jdewinne**

### CODE REVIEW

**Review by alexparker215 — APPROVED** [review]

**Comment by JMNordeste-dev** [comment]
@ajp-io @jdewinne @dexhorthy bit curious, but did we consider branding? I think we may want to consider as we moved away from this for the default file names:
image
to this (lots of KOTS which is a bit of a step backwards I think?):
image

Was this considered at all?

**Comment by alexparker215** [comment]
The file name changes weren't part of this change—that must have happened some time ago. But I agree that I prefer to not prefix with `kots-` since we're not using that language as much in the product.

**Comment by jdewinne** [comment]
@ajp-io This is to make it more readable. Especially if you use an IDE (with the replicated cli), having them prefixed makes it a lot easier to know which manifests are `kots` and which ones are actually making up the application.

**Comment by JMNordeste-dev** [comment]
@jdewinne since we don't use KOTS anymore though is there a better way? I had opened a branch with some suggestions though I don't know if it is much clearer (and it definitely feels like the names are too long in most cases) 
https://github.com/replicatedhq/kots-default-yaml/tree/justin-filerenames
Part of what I was trying to surface though was which component or reference material they could look at corresponding to each file (I know that all are in https://docs.replicated.com/reference/custom-resource-about but in some cases I figured plugging troubleshoot may be worthwhile)

**Pull request merged**
